# Config file for automatic testing at travis-ci.org

language: python

jobs:
  include:
    - env: TOXENV=py37
      name: "Python3.7 (Linux)"
      python: 3.7
      addons:
        apt:
          packages:
            - libudunits2-dev
    - env: TOXENV=py36
      name: "Python3.6 (Linux)"
      python: 3.6
      addons:
        apt:
          packages:
            - libudunits2-dev


before_install:
    - printenv
    - pip install --upgrade pip

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox -e $TOXENV


